[[action]]
type = "text"
text = "test"

[[action]]
type = "if"
condition = "equals"
compare_with = "test"

    [[action]]
    type = "show_result"
    text = "true!"

[[action]]
type = "else"

    [[action]]
    type = "show_result"
    text = "false :("

[[action]]
type = "endif"
